<?php

use Illuminate\Database\Seeder;

class BeeritemTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('beeritems')->insert([
            'id'                    => 1,
            'user_id'               => 2,
            'collection_id'         => 1,
            'brewery_id'            => 1,
            'category_id'           => 1,
            'item_type'             => 'beerglasses',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 1,
            'item_wishlist'         => false,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);

        DB::table('beeritems')->insert([
            'id'                    => 2,
            'user_id'               => 2,
            'collection_id'         => 2,
            'brewery_id'            => 2,
            'category_id'           => 2,
            'item_type'             => 'beerashtrays',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 2,
            'item_wishlist'         => true,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);

        DB::table('beeritems')->insert([
            'id'                    => 3,
            'user_id'               => 2,
            'collection_id'         => 3,
            'brewery_id'            => 1,
            'category_id'           => 1,
            'item_type'             => 'beercontainers',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 3,
            'item_wishlist'         => false,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);

        DB::table('beeritems')->insert([
            'id'                    => 4,
            'user_id'               => 2,
            'collection_id'         => 4,
            'brewery_id'            => 2,
            'category_id'           => 2,
            'item_type'             => 'beerlabels',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 1,
            'item_wishlist'         => true,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);

        DB::table('beeritems')->insert([
            'id'                    => 5,
            'user_id'               => 2,
            'collection_id'         => 5,
            'brewery_id'            => 1,
            'category_id'           => 1,
            'item_type'             => 'beerbottles',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 4,
            'item_wishlist'         => false,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);

        DB::table('beeritems')->insert([
            'id'                    => 6,
            'user_id'               => 2,
            'collection_id'         => 6,
            'brewery_id'            => 2,
            'category_id'           => 2,
            'item_type'             => 'beerplateaus',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 4,
            'item_wishlist'         => true,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);
        DB::table('beeritems')->insert([
            'id'                    => 7,
            'user_id'               => 2,
            'collection_id'         => 7,
            'brewery_id'            => 1,
            'category_id'           => 1,
            'item_type'             => 'beeradvertisements',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 3,
            'item_wishlist'         => false,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);

        DB::table('beeritems')->insert([
            'id'                    => 8,
            'user_id'               => 2,
            'collection_id'         => 8,
            'brewery_id'            => 2,
            'category_id'           => 2,
            'item_type'             => 'beercoasters',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 5,
            'item_wishlist'         => true,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);
        DB::table('beeritems')->insert([
            'id'                    => 9,
            'user_id'               => 2,
            'collection_id'         => 9,
            'brewery_id'            => 1,
            'category_id'           => 1,
            'item_type'             => 'beerstonejugs',
            'item_name'             => 'test',
            'item_description'      => 'test',
            'item_amount'           => 2,
            'item_wishlist'         => false,
            'item_type_1'           => 'test',
            'item_text'             => 'test',
            'item_color'            => 'test',
            'item_text_color'       => 'test',
            'item_type_print'       => 'test',
            'item_drawing'          => 'test',
            'item_cluster'          => 'test',
            'item_height'           => 20,
            'item_width'            => 30,
            'item_length'           => 40,
            'item_diameter_top'     => 5,
            'item_diameter_bottom'  => 3,
            'item_weight'           => 80,
            'item_size_indication'  => 'test',
            'item_rib_type'         => 'test',
            'item_facets'           => 'test',
            'item_model'            => 'test',
            'item_material'         => 'test',
            'item_year'             => now(),
            'item_language'         => 'test',
            'item_size'             => 20,
            'item_boxes'            => 'test',
            'item_extra_1'          => 'test',
            'item_extra_2'          => 'test',
            'created_at'            => now(),
            'updated_at'            => now()
        ]);
    }
}
